# Generated by Django 2.1.3 on 2018-11-15 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
