# Generated by Django 2.1.3 on 2018-11-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181115_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='Video_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
