# Generated by Django 2.1.3 on 2019-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20181115_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-Comment_data']},
        ),
        migrations.AddField(
            model_name='video',
            name='Video_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment_text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
